name: Update trackers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

defaults:
  run:
    shell: nu {0}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hustcer/setup-nu@main
        with:
          version: '*'

      - name: System dependencies
        run: pip install matplotlib

      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Update the trackers
        run: ./update-issue-trackers.nu

      - name: Some debug
        run: |
          git log --graph --branches --remotes --tags --oneline --decorate
          git remote --verbose show

      - name: Commit the change
        run: |
          git add .
          git commit -m $"update trackers (char lparen)(date now | format date "%Y-%m-%dT%H:%M:%S")(char rparen)"
          git push
